# Setup required targets before testing.
#TEST_DEPS := run-db
# Setup required targets before running commands.
#RUN_DEPS := run-db

TARGETS_LINT = lint-plus lint-codacy lint-markdown lint-apis

IMAGE_PUSH ?= never
TEST_TIMEOUT := 12s
